---
title: R-Ladies Meetup
author: Cécile Sauder
date: '2019-02-12'
topics:
  - R-Ladies
  - meetup
tags:
  - slides
  - xaringan
  - tidyverse
slug: rladies-meetups
header: "img/rladies.svg"
---



# R-Ladies Montpellier meetups

Since december 2018, I co-organised with [Criscely](https://twitter.com/CriscelyLP) the R-Ladies Montpellier [meetups](https://www.meetup.com/fr-FR/rladies-montpellier/). 

You can follow R-Ladies Montpellier on [twitter](https://twitter.com/RLadiesMontpel) and [github](https://github.com/r-ladies-montpellier).

Here are my slides (made with xaringan) : 

  - [Meetup 1]() :

```{r, echo=FALSE}
#https://cecilesauder.netlify.com/RLadiesMeetups/meetup1_Tidyverse/Tidyverse.html
#knitr::include_url('https://cecilesauder.netlify.com/RLadiesMeetups/meetup1_Tidyverse/tidyverse#1')
```


  - [Meetup 2](https://cecilesauder.netlify.com/RLadiesMeetups/meetup2_Tidyverse_exercises/Tidyverse_exercises.html) : 
  
```{r, echo=FALSE}

knitr::include_url('https://cecilesauder.netlify.com/rladiesmeetups/meetup2_tidyverse_exercises/tidyverse_exercises#1')
```
